# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "Llama 3 debug training"
use_for_integration_test = true

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_color_printing = false
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "debugmodel"
norm_type = "fused_rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
# test tokenizer.model, for debug purpose only
tokenizer_path = "./torchtitan/datasets/tokenizer/original/tokenizer.model" #"./test/assets/test_tiktoken.model"

[optimizer]
name = "adam_mini" #"AdamW" #"adam_mini" #"AdamW" 
lr = 8e-4

[training]
batch_size = 2 #8
seq_len = 2048
warmup_steps = 20  # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0  # grad norm clipping
steps = 40
data_parallel_degree = -1
tensor_parallel_degree = 1
fp8_linear = ""
compile = false
dataset = "c4_mini"  # supported datasets: c4_mini (45K), c4 (177M)
dataset_path = "./torchtitan/datasets/c4_mini/"

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder =  "/mntcephfs/lab_data/zhangyushun/torchtitan/llama3_8b" #"checkpoint"
interval_type = "steps"
interval = 50000000000
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'none'  # ['none', 'selective', 'full']
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy
